### ISSUE TITLE
theming?

### ISSUE THREAD

**Issue by anarcat** [Pext/Pext#10]
is there a way to change the colors and look of pext?

**Comment by TheLastProject** [comment]
Pext is a Qt5 application, so should inherit your Qt5 theming. For now, you can change your system Qt theme, or put something like ``QT_STYLE_OVERRIDE=adwaita`` in front of the command line argument you use to start Pext.

In the future I do want to see if I can retrieve a list of systems themes so you can choose one from a drop-down menu in the top bar, or possibly see if I can add support for more "custom" themes using [Qt Style Sheets](https://doc.qt.io/qt-5/stylesheet-reference.html).

**Comment by TheLastProject** [comment]
35c255f2fb334651a2ad8c17cd802f6e1b989d09 implements the very basics to select a theme from the command line. Not all supported Qt5 themes are currently listed due to PyQt5 limitations, but it's a start. I'm leaving this issue open until I feel there is enough proper theming support.

**Comment by zamber** [comment]
There's a better way to style it under GTK.

1. https://wiki.archlinux.org/index.php/qt#Qt5
2. https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications#QGtkStyle
3. `sudo apt install qt5-style-plugins`
4. Make sure you have `qt5ct` (there's an Ubuntu PPA for it available).
5. Open `qt5ct` adn set the `GTK+` theme.
6. ...
7. PROFIT (now Qt5 apps should use your GTK theme).
8. BONUS: when you're at it, change the fonts and icons in `qt5ct` to match your system settings.

**Comment by TheLastProject** [comment]
Having researched more about this, there seem to be several possibilities to let users theme Pext to their wishes beyond @zamber's note. Putting this here for my own reference and in the hope someone may be able to help figure out what Telegram is doing and how possible that would be.

### Qt Stylesheets (https://doc.qt.io/qt-5/stylesheet.html)
Just like CSS, pretty awesome and powerful-looking. However, not natively supported in QML and will need https://github.com/Ableton/aqt-stylesheets, a C++ plugin. Shipping this with Pext as a binary is obviously not an option, so this route will require setting up something like [OpenBuildSystem](https://build.opensuse.org/) so users can get binaries that will just work and the source code stays clean from binaries. While the most powerful solution, it is rather heavy-weight.

### QML Style Singleton (https://wiki.qt.io/Qml_Styling#Approach_2:_Style_Singleton)
Not really a great solution. Bad code here will crash the whole app and thus make themes able to crash Pext as a whole. Also won't style dialog boxes and so that aren't part of the QML.

### QPalette (https://doc.qt.io/qt-5/qpalette.html)
Simple solution, but very weak, would only allow users to change the colour of some text elements, basically. This is barely theming.

### Figure out whatever Telegram is doing
There solution involves .tdesktop-theme files which are .zip files containing a background image and [something which seems like just a list of colours to use for everything](https://github.com/telegramdesktop/tdesktop/blob/22d905b39c6d0f535748043c11c0da9b19c388a1/Telegram/Resources/colors.palette). No clue if something like this can be used for Pext.

**Comment by TheLastProject** [comment]
I started theming support based on QPalette in the feature/theming branch.

A basic theming file (which can already be loaded if put in ~/.config/pext/themes/pext_theme_dark/theme.conf and calling Pext with --theme=dark) will look like this:
```
Window: 53,53,53
WindowText: 0,0,0
Base: 25,25,25
AlternateBase: 53,53,53
ToolTipBase: 0,0,0 
ToolTipText: 0,0,0 
Text: 0,0,0 
Button: 53,53,53
ButtonText: 0,0,0
BrightText: 255,0,0
Link: 42,130,218
Highlight: 42,130,218
HighlightedText: 255,255,255
```
(This was based on https://gist.github.com/QuantumCD/6245215 for testing purposes)

It's still rather crude, but this seems to be the best way to go.

**Comment by TheLastProject** [comment]
As of 687da11de9b6eb3b239ba5d02357d008faa6d3e5 I consider this fixed. I'll create a new issue about writing documentation for this. See https://github.com/Pext/pext_theme_eggplant for an example.
