### ISSUE TITLE
Make it localizable.

### ISSUE THREAD

**Issue by s8321414** [Pext/Pext#12]
As title says, hope we can see translation version for this tool 😄

**Comment by TheLastProject** [comment]
This is definitely a great idea. I'll do some research on what would be the best way to do this, also for modules themselves. QLinguist would be a logical choice, as this is a Qt app, but I'd also like to see if I can find something that doesn't necessarily need Qt so that if Pext could maybe one day support choosing between Qt and GTK+ or so that this won't be a problem. Preferably something supported by Weblate so Weblate can be used to manage translations so translators don't have to code.

**Comment by TheLastProject** [comment]
Okay, this is definitely going to take a while. To put it kindly, PyQt's i18n stack is not as functional as the standard Qt i18n stack. I still want to do this but yeah, don't expect it any time soon.

**Comment by TheLastProject** [comment]
Should be all ready now, just need to wait for Weblate to flip a last switch :)

**Comment by richarson** [comment]
Cool!

I just signed into Weblate.
Can I request a spanish translation and start translating?

**Comment by TheLastProject** [comment]
Unfortunately not yet. Weblate is still set to the i18n branch from when I was trying some other i18n method that ended up not working. We just need to wait for the Weblate dev to switch the project to the master branch, which I unfortunately can't do myself on the hosted instance. As soon as that has happened I'll leave a comment on this issue, close it and add a Weblate link to the README. Thanks for your interest by the way :)

**Comment by richarson** [comment]
OK, I'll wait then :)

**Comment by TheLastProject** [comment]
Eh, I got tired waiting for the configuration change I wanted, so I decided to just roll with the current setup. Translations can be done on https://hosted.weblate.org/projects/pext/translations/. Thanks for your help!

**Comment by TheLastProject** [comment]
I noticed that the logged messages about module updating/installing/uninstalling are currently not translatable. I'm reopening this issue until I find the time to fix this. If someone else sees a nice way to fix that bit, patches are of course welcome!

**Comment by TheLastProject** [comment]
Instead of making these translatable, I've chosen to simply replace these messages with unicode symbols in 2ff5102d8d393aa2474590f2fbbed918e5743687 as those should be reasonable language-independent. It's not a perfect solution and i may very well have accidentally used symbols that don't have the same meaning cross-culture (please tell me if you have recommendations for other icons!), but it seems good enough of a workaround (around PyQt5 limitations) for now to consider translations fully supported.

If you're a translator, please make sure to hit the "Watch" button on https://hosted.weblate.org/projects/pext/ on Weblate so that you'll receive email notifications when there are new translations.

On that note, thank you @Vistaus and @s8321414 for your translations so far, it'd be great to keep seeing translations from you both coming in, and hopefully have other translators join :)

**Comment by s8321414** [comment]
You're welcome 😄

**Comment by Vistaus** [comment]
Sure, no problem! 😄
