### ISSUE TITLE
Add a back button?

### ISSUE THREAD

**Issue by rseward** [Pext/Pext#13]
I have written a custom module, that executes a script returns some JSON. I parse the JSON and display results. I can select a result entry to examine. Pext renders my result entry when I select it. However there is not a good way (in the UI [that I can see]) to return to my result set. (A back button perhaps?)

I could create a "mlocate" module or similar to demonstrate the awkwardness of this use case. 

Also what is the best way to reset your query? E.g. to start over. The best I have found is "ESC". A reset button might be useful to visually indicate you can reset your query.

Ideally, I would think every time you hit the "enter" key, the app should reload query results. But this doesn't seem to be the case. Perhaps because the project is still maturing? Or perhaps the behavior is intentional that your response does not change until you type "ESC".

**Comment by TheLastProject** [comment]
a3049476a32e334143b8b12f1b20afdece080d6e adds a simple clear/back button which addresses the main part of your issue. I'm going to close this issue now for my own personal administration so that it's clear that a back button has been added, but please re-open it if you get a chance to explain your last statement because I do want to assist where I can.

Thank you for your report.
