### ISSUE TITLE
Suggestions for Pext modules

### ISSUE THREAD

**Issue by jangondol** [Pext/Pext#3]
:heart: Pext, looks super useful!

What is a good place to collect ideas about potentially interesting modules (if some developers would like to pick them up and implement them or suggest improvements)? How about collecting suggestions in this issue + creating **one issue per suggested module**? Should this discussion happen here or should a separate repo be created for this?

**Comment by TheLastProject** [comment]
Thanks for your interest in Pext :)

Suggested improvements to a specific module should happen on the issue tracker for the module itself. For new module suggestions, I feel that having one issue per suggested module is best, I'll create a suggested-module label on GitHub to tag these with so it's easy to keep module suggestions and bugs separated. Let's just keep that on this issue tracker for now.

Do note that, while the API is getting increasingly stable, I do still sometimes break it and will likely continue to keep doing so occasionally until a 1.0 release, especially because every now and then some API limitation prevents a cool module idea from being possible. So, while module development is very much possible, developers should expect the possibility of their modules randomly breaking on an update.

I'm not sure about using a single issue to collect suggestions, but I'll just leave it open as a meta issue as long as it doesn't get too chaotic.

**Comment by TheLastProject** [comment]
Well, it's been over 3 years and nobody ever used this issue, so I'll close it to clean up the bugtracker a bit :)
