### ISSUE TITLE
Plugin installation failure yields return code 0

### ISSUE THREAD

**Issue by TheAssassin** [Pext/Pext#34]
See https://travis-ci.org/Pext/Pext/jobs/295989017#L4811-L4822.

Pext should exit with an exit status != 0 when plugin installations fail. That'll make testing its functionality on build services like Travis a lot easier.

**Comment by TheAssassin** [comment]
Turned out in some cases Pext does return an error state, see https://travis-ci.org/Pext/Pext/jobs/295994548#L4922-L4932.

**Comment by TheLastProject** [comment]
Note to self: this only applies to installing from the command line.

Have to decide on making --exit exit with the right error code (easier to run multiple commands), or getting rid of --exit completely and just not trying to start the GUI at all when doing stuff like installing modules from the command line. I'll fix this as soon as I've decided what way I want to go here.

**Comment by TheAssassin** [comment]
Thanks for looking into this. There's no rush, the error I wanted to check for on Travis (which can be found in the second link) yields the right exit code. I just wanted to note that this behavior should be consistent.

**Comment by TheLastProject** [comment]
Fixed in 7ac8cfce0c1dadf4ac55c1abc355e0ea09d61358, --exit is no longer a valid command line argument and Pext exits with 0 after processing all arguments (as long as they don't all relate to the current session, like --profile=development or so, in which case Pext launches its UI). If any requested argument failed, it exits with a non-zero exit code immediately after the failing argument and will not process further arguments.

I think this behaviour is most consistent with what people expect of CLI usage.

**Comment by TheAssassin** [comment]
Thanks!
