### ISSUE TITLE
Support online banking

### ISSUE THREAD

**Issue by pudo** [Pext/Pext#8]
I haven't quite figured out what Pext is, but it definitely needs online banking.

**Comment by TheLastProject** [comment]
While I am not going to write any modules for something this sensitive, it would be cool if someone wrote modules using bank APIs to check your credit and transfer money and so (because gosh, most bank sites are horrid). No reason this wouldn't be possible. Don't know any bank with a reasonable API from the top of my head though.

**Comment by shymega** [comment]
Hi,
There are some online banking APIs avaliable, but I _believe_ they are in quite early development. Might be worth bearing in mind, however.. there's [Teller.io][teller], which AFAICT, is UK-based- possibly still worth a look, and [Open Bank Project][openbankproj], which doesn't **appear** to be UK-specific, so perhaps a better choice. These are all projects I've looked into briefely when I've tried to integrate my bank's data with ledger-cli - to no avail. HTH.

[teller]: https://teller.io/
[openbankproj]: https://openbankproject.com/

**Comment by HarolddeBruijn** [comment]
The bunq api might be worth while to give a glance. https://doc.bunq.com/

**Comment by TheLastProject** [comment]
Seeing as this issue has been stale for over 2 and a half years, I'll go and close it. If anyone ever wants to get started with something like this, I'm willing to help assist.
